### ISSUE TITLE
Using package without CUDA

### ISSUE THREAD

**Issue by asiliskins** [ruanchaves/hashformers#32]
Hi, great work! Is it possible to use hashformers without CUDA enabled for torch?

**Comment by ruanchaves** [comment]
@asiliskins After the release of version 2.0, `hashformers` now supports any valid device as `segmenter_device` or `reranker_device`:

```
from hashformers import TransformerWordSegmenter as WordSegmenter
ws = WordSegmenter(
    segmenter_model_name_or_path="gpt2",
    segmenter_model_type="incremental",
    segmenter_device="cpu",
    reranker_device="cpu",
    segmenter_gpu_batch_size=100,
    reranker_gpu_batch_size=100,
    reranker_model_name_or_path="bert-base-cased",
    reranker_model_type="masked"
)
```

Note: The `segmenter_gpu_batch_size` and `reranker_gpu_batch_size` parameters set the batch size on the CPU if segmenter_device and reranker_device are set to `cpu` instead of `cuda`. These arguments retain their original names for backward compatibility with previous library versions.
